-- 047: 演示数据的可读 ID（demo-*/seed-*）换成合法 UUID，否则报名等接口的 UUID 校验会拦掉
-- 幂等：跑过后 demo ID 已全部替换，再跑就是空操作
WITH map_User AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "User" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Instructor AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Instructor" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Student AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Student" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_ParentStudentLink AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "ParentStudentLink" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Campus AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Campus" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Course AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Course" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Term AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Term" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_CourseCampus AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "CourseCampus" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_CourseInstructor AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "CourseInstructor" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_ClassSession AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "ClassSession" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Enrollment AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Enrollment" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Notice AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Notice" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Event AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Event" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_EventRegistration AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "EventRegistration" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_EventRegistrationOrder AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "EventRegistrationOrder" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_ReminderRule AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "ReminderRule" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_ReminderLog AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "ReminderLog" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Order AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Order" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_OrderItem AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "OrderItem" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Payment AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Payment" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_RefundRecord AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "RefundRecord" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_SessionOccurrence AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "SessionOccurrence" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Holiday AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Holiday" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_OccurrenceCancelRequest AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "OccurrenceCancelRequest" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_AttendanceRecord AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "AttendanceRecord" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_MakeupEligibility AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "MakeupEligibility" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_MakeupBooking AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "MakeupBooking" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_ExtraLessonRequest AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "ExtraLessonRequest" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_ExtraLessonSlot AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "ExtraLessonSlot" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_CourseReview AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "CourseReview" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_StudentReview AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "StudentReview" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_InstructorCheckin AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "InstructorCheckin" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_MessageThread AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "MessageThread" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Message AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Message" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_MessageTemplate AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "MessageTemplate" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Document AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Document" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_DocumentSignature AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "DocumentSignature" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_DocumentSend AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "DocumentSend" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_DocumentSendRecipient AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "DocumentSendRecipient" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
map_Notification AS (SELECT "id" AS old_id, gen_random_uuid()::text AS new_id FROM "Notification" WHERE "id" LIKE 'demo-%' OR "id" LIKE 'demo2-%' OR "id" LIKE 'demo3-%' OR "id" LIKE 'seed-%'),
upd_fk_0 AS (UPDATE "Instructor" SET "userId" = m.new_id FROM map_User m WHERE "Instructor"."userId" = m.old_id),
upd_fk_1 AS (UPDATE "Instructor" SET "defaultCampusId" = m.new_id FROM map_Campus m WHERE "Instructor"."defaultCampusId" = m.old_id),
upd_fk_2 AS (UPDATE "ParentStudentLink" SET "parentId" = m.new_id FROM map_User m WHERE "ParentStudentLink"."parentId" = m.old_id),
upd_fk_3 AS (UPDATE "ParentStudentLink" SET "studentId" = m.new_id FROM map_Student m WHERE "ParentStudentLink"."studentId" = m.old_id),
upd_fk_4 AS (UPDATE "Course" SET "termId" = m.new_id FROM map_Term m WHERE "Course"."termId" = m.old_id),
upd_fk_5 AS (UPDATE "Course" SET "sourceCourseId" = m.new_id FROM map_Course m WHERE "Course"."sourceCourseId" = m.old_id),
upd_fk_6 AS (UPDATE "CourseCampus" SET "courseId" = m.new_id FROM map_Course m WHERE "CourseCampus"."courseId" = m.old_id),
upd_fk_7 AS (UPDATE "CourseCampus" SET "campusId" = m.new_id FROM map_Campus m WHERE "CourseCampus"."campusId" = m.old_id),
upd_fk_8 AS (UPDATE "CourseInstructor" SET "courseId" = m.new_id FROM map_Course m WHERE "CourseInstructor"."courseId" = m.old_id),
upd_fk_9 AS (UPDATE "CourseInstructor" SET "instructorId" = m.new_id FROM map_Instructor m WHERE "CourseInstructor"."instructorId" = m.old_id),
upd_fk_10 AS (UPDATE "ClassSession" SET "courseId" = m.new_id FROM map_Course m WHERE "ClassSession"."courseId" = m.old_id),
upd_fk_11 AS (UPDATE "ClassSession" SET "campusId" = m.new_id FROM map_Campus m WHERE "ClassSession"."campusId" = m.old_id),
upd_fk_12 AS (UPDATE "ClassSession" SET "instructorId" = m.new_id FROM map_Instructor m WHERE "ClassSession"."instructorId" = m.old_id),
upd_fk_13 AS (UPDATE "Enrollment" SET "classSessionId" = m.new_id FROM map_ClassSession m WHERE "Enrollment"."classSessionId" = m.old_id),
upd_fk_14 AS (UPDATE "Enrollment" SET "studentId" = m.new_id FROM map_Student m WHERE "Enrollment"."studentId" = m.old_id),
upd_fk_15 AS (UPDATE "Enrollment" SET "enrolledByParentId" = m.new_id FROM map_User m WHERE "Enrollment"."enrolledByParentId" = m.old_id),
upd_fk_16 AS (UPDATE "Notice" SET "createdById" = m.new_id FROM map_User m WHERE "Notice"."createdById" = m.old_id),
upd_fk_17 AS (UPDATE "Event" SET "campusId" = m.new_id FROM map_Campus m WHERE "Event"."campusId" = m.old_id),
upd_fk_18 AS (UPDATE "EventRegistration" SET "eventId" = m.new_id FROM map_Event m WHERE "EventRegistration"."eventId" = m.old_id),
upd_fk_19 AS (UPDATE "EventRegistration" SET "studentId" = m.new_id FROM map_Student m WHERE "EventRegistration"."studentId" = m.old_id),
upd_fk_20 AS (UPDATE "EventRegistration" SET "parentId" = m.new_id FROM map_User m WHERE "EventRegistration"."parentId" = m.old_id),
upd_fk_21 AS (UPDATE "EventRegistrationOrder" SET "eventRegistrationId" = m.new_id FROM map_EventRegistration m WHERE "EventRegistrationOrder"."eventRegistrationId" = m.old_id),
upd_fk_22 AS (UPDATE "EventRegistrationOrder" SET "orderId" = m.new_id FROM map_Order m WHERE "EventRegistrationOrder"."orderId" = m.old_id),
upd_fk_23 AS (UPDATE "ReminderLog" SET "ruleId" = m.new_id FROM map_ReminderRule m WHERE "ReminderLog"."ruleId" = m.old_id),
upd_fk_24 AS (UPDATE "ReminderLog" SET "recipientId" = m.new_id FROM map_User m WHERE "ReminderLog"."recipientId" = m.old_id),
upd_fk_25 AS (UPDATE "Order" SET "parentId" = m.new_id FROM map_User m WHERE "Order"."parentId" = m.old_id),
upd_fk_26 AS (UPDATE "OrderItem" SET "orderId" = m.new_id FROM map_Order m WHERE "OrderItem"."orderId" = m.old_id),
upd_fk_27 AS (UPDATE "OrderItem" SET "enrollmentId" = m.new_id FROM map_Enrollment m WHERE "OrderItem"."enrollmentId" = m.old_id),
upd_fk_28 AS (UPDATE "OrderItem" SET "eventRegistrationId" = m.new_id FROM map_EventRegistration m WHERE "OrderItem"."eventRegistrationId" = m.old_id),
upd_fk_29 AS (UPDATE "Payment" SET "orderId" = m.new_id FROM map_Order m WHERE "Payment"."orderId" = m.old_id),
upd_fk_30 AS (UPDATE "Payment" SET "recordedById" = m.new_id FROM map_User m WHERE "Payment"."recordedById" = m.old_id),
upd_fk_31 AS (UPDATE "RefundRecord" SET "orderId" = m.new_id FROM map_Order m WHERE "RefundRecord"."orderId" = m.old_id),
upd_fk_32 AS (UPDATE "RefundRecord" SET "orderItemId" = m.new_id FROM map_OrderItem m WHERE "RefundRecord"."orderItemId" = m.old_id),
upd_fk_33 AS (UPDATE "RefundRecord" SET "refundedById" = m.new_id FROM map_User m WHERE "RefundRecord"."refundedById" = m.old_id),
upd_fk_34 AS (UPDATE "SessionOccurrence" SET "classSessionId" = m.new_id FROM map_ClassSession m WHERE "SessionOccurrence"."classSessionId" = m.old_id),
upd_fk_35 AS (UPDATE "SessionOccurrence" SET "postponedToOccurrenceId" = m.new_id FROM map_SessionOccurrence m WHERE "SessionOccurrence"."postponedToOccurrenceId" = m.old_id),
upd_fk_36 AS (UPDATE "SessionOccurrence" SET "substituteInstructorId" = m.new_id FROM map_Instructor m WHERE "SessionOccurrence"."substituteInstructorId" = m.old_id),
upd_fk_37 AS (UPDATE "Holiday" SET "createdById" = m.new_id FROM map_User m WHERE "Holiday"."createdById" = m.old_id),
upd_fk_38 AS (UPDATE "OccurrenceCancelRequest" SET "occurrenceId" = m.new_id FROM map_SessionOccurrence m WHERE "OccurrenceCancelRequest"."occurrenceId" = m.old_id),
upd_fk_39 AS (UPDATE "OccurrenceCancelRequest" SET "instructorId" = m.new_id FROM map_Instructor m WHERE "OccurrenceCancelRequest"."instructorId" = m.old_id),
upd_fk_40 AS (UPDATE "OccurrenceCancelRequest" SET "reviewedById" = m.new_id FROM map_User m WHERE "OccurrenceCancelRequest"."reviewedById" = m.old_id),
upd_fk_41 AS (UPDATE "AttendanceRecord" SET "sessionOccurrenceId" = m.new_id FROM map_SessionOccurrence m WHERE "AttendanceRecord"."sessionOccurrenceId" = m.old_id),
upd_fk_42 AS (UPDATE "AttendanceRecord" SET "enrollmentId" = m.new_id FROM map_Enrollment m WHERE "AttendanceRecord"."enrollmentId" = m.old_id),
upd_fk_43 AS (UPDATE "AttendanceRecord" SET "confirmedById" = m.new_id FROM map_User m WHERE "AttendanceRecord"."confirmedById" = m.old_id),
upd_fk_44 AS (UPDATE "MakeupEligibility" SET "sourceClassSessionId" = m.new_id FROM map_ClassSession m WHERE "MakeupEligibility"."sourceClassSessionId" = m.old_id),
upd_fk_45 AS (UPDATE "MakeupEligibility" SET "eligibleClassSessionId" = m.new_id FROM map_ClassSession m WHERE "MakeupEligibility"."eligibleClassSessionId" = m.old_id),
upd_fk_46 AS (UPDATE "MakeupEligibility" SET "createdById" = m.new_id FROM map_User m WHERE "MakeupEligibility"."createdById" = m.old_id),
upd_fk_47 AS (UPDATE "MakeupBooking" SET "enrollmentId" = m.new_id FROM map_Enrollment m WHERE "MakeupBooking"."enrollmentId" = m.old_id),
upd_fk_48 AS (UPDATE "MakeupBooking" SET "missedOccurrenceId" = m.new_id FROM map_SessionOccurrence m WHERE "MakeupBooking"."missedOccurrenceId" = m.old_id),
upd_fk_49 AS (UPDATE "MakeupBooking" SET "makeupOccurrenceId" = m.new_id FROM map_SessionOccurrence m WHERE "MakeupBooking"."makeupOccurrenceId" = m.old_id),
upd_fk_50 AS (UPDATE "ExtraLessonRequest" SET "studentId" = m.new_id FROM map_Student m WHERE "ExtraLessonRequest"."studentId" = m.old_id),
upd_fk_51 AS (UPDATE "ExtraLessonRequest" SET "sourceCourseId" = m.new_id FROM map_Course m WHERE "ExtraLessonRequest"."sourceCourseId" = m.old_id),
upd_fk_52 AS (UPDATE "ExtraLessonRequest" SET "sourceEnrollmentId" = m.new_id FROM map_Enrollment m WHERE "ExtraLessonRequest"."sourceEnrollmentId" = m.old_id),
upd_fk_53 AS (UPDATE "ExtraLessonRequest" SET "instructorId" = m.new_id FROM map_Instructor m WHERE "ExtraLessonRequest"."instructorId" = m.old_id),
upd_fk_54 AS (UPDATE "ExtraLessonRequest" SET "createdById" = m.new_id FROM map_User m WHERE "ExtraLessonRequest"."createdById" = m.old_id),
upd_fk_55 AS (UPDATE "ExtraLessonRequest" SET "campusId" = m.new_id FROM map_Campus m WHERE "ExtraLessonRequest"."campusId" = m.old_id),
upd_fk_56 AS (UPDATE "ExtraLessonSlot" SET "requestId" = m.new_id FROM map_ExtraLessonRequest m WHERE "ExtraLessonSlot"."requestId" = m.old_id),
upd_fk_57 AS (UPDATE "CourseReview" SET "courseId" = m.new_id FROM map_Course m WHERE "CourseReview"."courseId" = m.old_id),
upd_fk_58 AS (UPDATE "CourseReview" SET "createdById" = m.new_id FROM map_User m WHERE "CourseReview"."createdById" = m.old_id),
upd_fk_59 AS (UPDATE "StudentReview" SET "classSessionId" = m.new_id FROM map_ClassSession m WHERE "StudentReview"."classSessionId" = m.old_id),
upd_fk_60 AS (UPDATE "StudentReview" SET "studentId" = m.new_id FROM map_Student m WHERE "StudentReview"."studentId" = m.old_id),
upd_fk_61 AS (UPDATE "StudentReview" SET "createdById" = m.new_id FROM map_User m WHERE "StudentReview"."createdById" = m.old_id),
upd_fk_62 AS (UPDATE "InstructorCheckin" SET "instructorId" = m.new_id FROM map_Instructor m WHERE "InstructorCheckin"."instructorId" = m.old_id),
upd_fk_63 AS (UPDATE "InstructorCheckin" SET "classSessionId" = m.new_id FROM map_ClassSession m WHERE "InstructorCheckin"."classSessionId" = m.old_id),
upd_fk_64 AS (UPDATE "InstructorCheckin" SET "sessionOccurrenceId" = m.new_id FROM map_SessionOccurrence m WHERE "InstructorCheckin"."sessionOccurrenceId" = m.old_id),
upd_fk_65 AS (UPDATE "InstructorCheckin" SET "extraLessonSlotId" = m.new_id FROM map_ExtraLessonSlot m WHERE "InstructorCheckin"."extraLessonSlotId" = m.old_id),
upd_fk_66 AS (UPDATE "MessageThread" SET "participantId" = m.new_id FROM map_User m WHERE "MessageThread"."participantId" = m.old_id),
upd_fk_67 AS (UPDATE "Message" SET "threadId" = m.new_id FROM map_MessageThread m WHERE "Message"."threadId" = m.old_id),
upd_fk_68 AS (UPDATE "Message" SET "senderId" = m.new_id FROM map_User m WHERE "Message"."senderId" = m.old_id),
upd_fk_69 AS (UPDATE "MessageTemplate" SET "createdById" = m.new_id FROM map_User m WHERE "MessageTemplate"."createdById" = m.old_id),
upd_fk_70 AS (UPDATE "Document" SET "supersedesDocumentId" = m.new_id FROM map_Document m WHERE "Document"."supersedesDocumentId" = m.old_id),
upd_fk_71 AS (UPDATE "Document" SET "createdById" = m.new_id FROM map_User m WHERE "Document"."createdById" = m.old_id),
upd_fk_72 AS (UPDATE "DocumentSignature" SET "documentId" = m.new_id FROM map_Document m WHERE "DocumentSignature"."documentId" = m.old_id),
upd_fk_73 AS (UPDATE "DocumentSignature" SET "studentId" = m.new_id FROM map_Student m WHERE "DocumentSignature"."studentId" = m.old_id),
upd_fk_74 AS (UPDATE "DocumentSignature" SET "signedById" = m.new_id FROM map_User m WHERE "DocumentSignature"."signedById" = m.old_id),
upd_fk_75 AS (UPDATE "DocumentSend" SET "documentId" = m.new_id FROM map_Document m WHERE "DocumentSend"."documentId" = m.old_id),
upd_fk_76 AS (UPDATE "DocumentSend" SET "createdById" = m.new_id FROM map_User m WHERE "DocumentSend"."createdById" = m.old_id),
upd_fk_77 AS (UPDATE "DocumentSendRecipient" SET "sendId" = m.new_id FROM map_DocumentSend m WHERE "DocumentSendRecipient"."sendId" = m.old_id),
upd_fk_78 AS (UPDATE "DocumentSendRecipient" SET "studentId" = m.new_id FROM map_Student m WHERE "DocumentSendRecipient"."studentId" = m.old_id),
upd_fk_79 AS (UPDATE "Notification" SET "userId" = m.new_id FROM map_User m WHERE "Notification"."userId" = m.old_id),
upd_pk_User AS (UPDATE "User" SET "id" = m.new_id FROM map_User m WHERE "User"."id" = m.old_id),
upd_pk_Instructor AS (UPDATE "Instructor" SET "id" = m.new_id FROM map_Instructor m WHERE "Instructor"."id" = m.old_id),
upd_pk_Student AS (UPDATE "Student" SET "id" = m.new_id FROM map_Student m WHERE "Student"."id" = m.old_id),
upd_pk_ParentStudentLink AS (UPDATE "ParentStudentLink" SET "id" = m.new_id FROM map_ParentStudentLink m WHERE "ParentStudentLink"."id" = m.old_id),
upd_pk_Campus AS (UPDATE "Campus" SET "id" = m.new_id FROM map_Campus m WHERE "Campus"."id" = m.old_id),
upd_pk_Course AS (UPDATE "Course" SET "id" = m.new_id FROM map_Course m WHERE "Course"."id" = m.old_id),
upd_pk_Term AS (UPDATE "Term" SET "id" = m.new_id FROM map_Term m WHERE "Term"."id" = m.old_id),
upd_pk_CourseCampus AS (UPDATE "CourseCampus" SET "id" = m.new_id FROM map_CourseCampus m WHERE "CourseCampus"."id" = m.old_id),
upd_pk_CourseInstructor AS (UPDATE "CourseInstructor" SET "id" = m.new_id FROM map_CourseInstructor m WHERE "CourseInstructor"."id" = m.old_id),
upd_pk_ClassSession AS (UPDATE "ClassSession" SET "id" = m.new_id FROM map_ClassSession m WHERE "ClassSession"."id" = m.old_id),
upd_pk_Enrollment AS (UPDATE "Enrollment" SET "id" = m.new_id FROM map_Enrollment m WHERE "Enrollment"."id" = m.old_id),
upd_pk_Notice AS (UPDATE "Notice" SET "id" = m.new_id FROM map_Notice m WHERE "Notice"."id" = m.old_id),
upd_pk_Event AS (UPDATE "Event" SET "id" = m.new_id FROM map_Event m WHERE "Event"."id" = m.old_id),
upd_pk_EventRegistration AS (UPDATE "EventRegistration" SET "id" = m.new_id FROM map_EventRegistration m WHERE "EventRegistration"."id" = m.old_id),
upd_pk_EventRegistrationOrder AS (UPDATE "EventRegistrationOrder" SET "id" = m.new_id FROM map_EventRegistrationOrder m WHERE "EventRegistrationOrder"."id" = m.old_id),
upd_pk_ReminderRule AS (UPDATE "ReminderRule" SET "id" = m.new_id FROM map_ReminderRule m WHERE "ReminderRule"."id" = m.old_id),
upd_pk_ReminderLog AS (UPDATE "ReminderLog" SET "id" = m.new_id FROM map_ReminderLog m WHERE "ReminderLog"."id" = m.old_id),
upd_pk_Order AS (UPDATE "Order" SET "id" = m.new_id FROM map_Order m WHERE "Order"."id" = m.old_id),
upd_pk_OrderItem AS (UPDATE "OrderItem" SET "id" = m.new_id FROM map_OrderItem m WHERE "OrderItem"."id" = m.old_id),
upd_pk_Payment AS (UPDATE "Payment" SET "id" = m.new_id FROM map_Payment m WHERE "Payment"."id" = m.old_id),
upd_pk_RefundRecord AS (UPDATE "RefundRecord" SET "id" = m.new_id FROM map_RefundRecord m WHERE "RefundRecord"."id" = m.old_id),
upd_pk_SessionOccurrence AS (UPDATE "SessionOccurrence" SET "id" = m.new_id FROM map_SessionOccurrence m WHERE "SessionOccurrence"."id" = m.old_id),
upd_pk_Holiday AS (UPDATE "Holiday" SET "id" = m.new_id FROM map_Holiday m WHERE "Holiday"."id" = m.old_id),
upd_pk_OccurrenceCancelRequest AS (UPDATE "OccurrenceCancelRequest" SET "id" = m.new_id FROM map_OccurrenceCancelRequest m WHERE "OccurrenceCancelRequest"."id" = m.old_id),
upd_pk_AttendanceRecord AS (UPDATE "AttendanceRecord" SET "id" = m.new_id FROM map_AttendanceRecord m WHERE "AttendanceRecord"."id" = m.old_id),
upd_pk_MakeupEligibility AS (UPDATE "MakeupEligibility" SET "id" = m.new_id FROM map_MakeupEligibility m WHERE "MakeupEligibility"."id" = m.old_id),
upd_pk_MakeupBooking AS (UPDATE "MakeupBooking" SET "id" = m.new_id FROM map_MakeupBooking m WHERE "MakeupBooking"."id" = m.old_id),
upd_pk_ExtraLessonRequest AS (UPDATE "ExtraLessonRequest" SET "id" = m.new_id FROM map_ExtraLessonRequest m WHERE "ExtraLessonRequest"."id" = m.old_id),
upd_pk_ExtraLessonSlot AS (UPDATE "ExtraLessonSlot" SET "id" = m.new_id FROM map_ExtraLessonSlot m WHERE "ExtraLessonSlot"."id" = m.old_id),
upd_pk_CourseReview AS (UPDATE "CourseReview" SET "id" = m.new_id FROM map_CourseReview m WHERE "CourseReview"."id" = m.old_id),
upd_pk_StudentReview AS (UPDATE "StudentReview" SET "id" = m.new_id FROM map_StudentReview m WHERE "StudentReview"."id" = m.old_id),
upd_pk_InstructorCheckin AS (UPDATE "InstructorCheckin" SET "id" = m.new_id FROM map_InstructorCheckin m WHERE "InstructorCheckin"."id" = m.old_id),
upd_pk_MessageThread AS (UPDATE "MessageThread" SET "id" = m.new_id FROM map_MessageThread m WHERE "MessageThread"."id" = m.old_id),
upd_pk_Message AS (UPDATE "Message" SET "id" = m.new_id FROM map_Message m WHERE "Message"."id" = m.old_id),
upd_pk_MessageTemplate AS (UPDATE "MessageTemplate" SET "id" = m.new_id FROM map_MessageTemplate m WHERE "MessageTemplate"."id" = m.old_id),
upd_pk_Document AS (UPDATE "Document" SET "id" = m.new_id FROM map_Document m WHERE "Document"."id" = m.old_id),
upd_pk_DocumentSignature AS (UPDATE "DocumentSignature" SET "id" = m.new_id FROM map_DocumentSignature m WHERE "DocumentSignature"."id" = m.old_id),
upd_pk_DocumentSend AS (UPDATE "DocumentSend" SET "id" = m.new_id FROM map_DocumentSend m WHERE "DocumentSend"."id" = m.old_id),
upd_pk_DocumentSendRecipient AS (UPDATE "DocumentSendRecipient" SET "id" = m.new_id FROM map_DocumentSendRecipient m WHERE "DocumentSendRecipient"."id" = m.old_id),
upd_pk_Notification AS (UPDATE "Notification" SET "id" = m.new_id FROM map_Notification m WHERE "Notification"."id" = m.old_id)
SELECT 1;
